apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-new-entity
  title: Create a Pull Request for a new added component in Kolibri
  description: Automates the PR process for adding a new entity in GitHub.
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Entity Information
      required:
        - name
        - type
        - owner
      properties:
        name:
          title: Entity Name
          type: string
          description: The unique name of the entity
        type:
          title: Entity Type
          type: string
          description: Choose an existing type or enter a new one
          enum: [components, apis, systems]
          default: components
        owner:
          title: Owner
          type: string
          description: Who owns this entity?
          default: team-kolibri
        jiraTicket:
          title: JIRA Ticket ID
          type: string
          default: BUILD-123
          description: Enter the JIRA ticket ID (e.g., BUILD-123)
        reviewers:
          title: Reviewers (Optional)
          type: array
          items:
            type: string
          default: [mec-endava]
          description: GitHub usernames of the reviewers (leave empty for default)

  steps:
    - id: fetch-template
      name: Determine Folder Path
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./catalog/${{ parameters.type }}/${{ parameters.name }}
        values:
          name: ${{ parameters.name }}
          type: ${{ parameters.type }}
          owner: ${{ parameters.owner }}

    - id: create-pr
      name: Open a PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=AndraMaximE&repo=kolibri-backstage-catalog
        title: "Add new ${{ parameters.type }} named ${{ parameters.name }}"
        description: This PR adds a new ${{ parameters.type }}, named `${{ parameters.name }}` to the Kolibri catalog.
        branchName: feature/${{ parameters.jiraTicket }}-${{ parameters.name }}
        targetBranchName: master
        commitMessage: "${{ parameters.jiraTicket }} Add new ${{ parameters.type }} named ${{ parameters.name }}"
        reviewers: ${{ parameters.reviewers }}
        update: true
  
  # output:
  #   links:
  #     - title: View PR
  #       url: https://github.com/${{ parameters.repoOwner }}/${{ parameters.repoName }}/pulls
