apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-backstage-app
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
  includes:
    - ./examples/create-new-repo/template.yaml
    - ./examples/create-pr-template/template.yaml