apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.repoName }}
  description: ${{ values.description }}
spec:
  type: website
  lifecycle: production
  owner: ${{ values.repoOwner }}
